services:
  - type: web
    name: energy-loss
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webui.py --host 0.0.0.0
    healthCheckPath: /
